name: Compile ESP32-S3 Firmware

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index
          arduino-cli config init --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32s3 --export-binaries Nano_duabe/Nano_duabe.ino

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: Nano_duabe/build/esp32.esp32.esp32s3/*.bin

